<a href="https://colab.research.google.com/github/jyotidabass/Health_data-pre-processing/blob/main/Health_data_pre_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [30]:
# Import required libraries

import numpy as np

import pandas as pd

In [31]:
# Create an example dataset

import pandas as pd

df = pd.DataFrame([
                ['Large', 'Sometimes good and sometimes bad', 'Stable','Combination skin', 1.1 ],
                ['Medium', 'Mostly sound and restful', 'Gaining', 'Mostly dry, no lubrication', 2.1],
                ['Thin', 'Mostly disturbed', 'Loosing', 'Mostly clear and oily', 3.1],
                ['Large', 'Sometimes good and sometimes bad', 'Stable', 'Combination skin', 1.1]])

df.columns = ['Build', 'Sleep', 'Weight_status', 'Skin', 'Response(Range)']

In [32]:
# View the first few rows of the dataset

df.head()

Build                             Sleep Weight_status  \
0   Large  Sometimes good and sometimes bad        Stable   
1  Medium          Mostly sound and restful       Gaining   
2    Thin                  Mostly disturbed       Loosing   
3   Large  Sometimes good and sometimes bad        Stable   

                         Skin  Response(Range)  
0            Combination skin              1.1  
1  Mostly dry, no lubrication              2.1  
2       Mostly clear and oily              3.1  
3            Combination skin              1.1

In [33]:
# View the summary of dataframe df

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   Build            4 non-null      object 
 1   Sleep            4 non-null      object 
 2   Weight_status    4 non-null      object 
 3   Skin             4 non-null      object 
 4   Response(Range)  4 non-null      float64
dtypes: float64(1), object(4)
memory usage: 288.0+ bytes
None


In [34]:
# View the descriptive statistics

print(df.describe())

       Response(Range)
count         4.000000
mean          1.850000
std           0.957427
min           1.100000
25%           1.100000
50%           1.600000
75%           2.350000
max           3.100000


In [35]:
# Make a copy of the dataframe df

df1 = df.copy()

# I have made a copy of the dataframe df as df1.

# Now, I will work with df1.

In [36]:
# View the first few rows of dataframe df1

df1.head()

Build                             Sleep Weight_status  \
0   Large  Sometimes good and sometimes bad        Stable   
1  Medium          Mostly sound and restful       Gaining   
2    Thin                  Mostly disturbed       Loosing   
3   Large  Sometimes good and sometimes bad        Stable   

                         Skin  Response(Range)  
0            Combination skin              1.1  
1  Mostly dry, no lubrication              2.1  
2       Mostly clear and oily              3.1  
3            Combination skin              1.1

In [37]:
# Encode Court Speed column labels into integer values

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y1 = le.fit_transform(df1['Skin'].values)

print("Encoded Skin column labels are:\n", (y1))

Encoded Skin column labels are:
 [0 2 1 0]


In [38]:
# Print class labels

print("The class labels are:\n", (le.classes_))

The class labels are:
 ['Combination skin' 'Mostly clear and oily' 'Mostly dry, no lubrication']


In [39]:
# Suppress future warnings

import warnings

warnings.simplefilter(action = "ignore", category = DeprecationWarning)

In [40]:
# Invert the encoded class labels to original class labels

print("The inverted original class labels are:\n",
      le.inverse_transform([0,2,1,0]))

The inverted original class labels are:
 ['Combination skin' 'Mostly dry, no lubrication' 'Mostly clear and oily'
 'Combination skin']


In [41]:
# Encode Build column values into integer values

X1 = df1[['Build', 'Response(Range)']].values

title_le = LabelEncoder()

X1[:, 0] = title_le.fit_transform(X1[:, 0])

print(X1)

[[0 1.1]
 [1 2.1]
 [2 3.1]
 [0 1.1]]


In [42]:
# Encode the converted integer values of Build column values into one-hot vectors

from sklearn.preprocessing import OneHotEncoder

ohe = OneHotEncoder()

ohe.fit_transform(X1).toarray()

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0.]])

In [43]:
# Copy the dataframe df2

df2 = df.copy()

In [44]:
# View the first few rows of df2

df2.head()

Build                             Sleep Weight_status  \
0   Large  Sometimes good and sometimes bad        Stable   
1  Medium          Mostly sound and restful       Gaining   
2    Thin                  Mostly disturbed       Loosing   
3   Large  Sometimes good and sometimes bad        Stable   

                         Skin  Response(Range)  
0            Combination skin              1.1  
1  Mostly dry, no lubrication              2.1  
2       Mostly clear and oily              3.1  
3            Combination skin              1.1

In [21]:
# Slice the Response column

X2 = df2.iloc[:, 4]

In [45]:
X2.head()

0    1
1    2
2    3
3    1
Name: Response(Range), dtype: int64

In [46]:
# Change the data type of X2 to integer 64

X2 = X2.astype('int64')

In [47]:
# Check the data type of X2

X2.dtype

dtype('int64')

In [25]:
# Encode X2 into one-hot-vectors with LabelBinarizer

from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()

y2 = lb.fit_transform(X2)

print(y2)

[[1 0 0]
 [0 1 0]
 [0 0 1]
 [1 0 0]]


In [48]:
print("The class labels are:\n", lb.classes_)

The class labels are:
 [1 2 3]


In [50]:
Health_df = [ 
            {'Build': 'Large', 'Response': 1.1},
            {'Build': 'Medium',     'Response': 2.1},
            {'Build': 'Thin',       'Response': 3.1},
            {'Build': 'Large',         'Response': 1.1}
        ]

# We can use DictVectorizer to do a binary one-hot encoding

from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer(sparse = False)

X_dv = dv.fit_transform(Health_df)

print(X_dv)

[[1.  0.  0.  1.1]
 [0.  1.  0.  2.1]
 [0.  0.  1.  3.1]
 [1.  0.  0.  1.1]]


In [51]:
# inspect the feature names

print("The feature names of Health_df data structure are:\n" , dv.get_feature_names())

The feature names of Health_df data structure are:
 ['Build=Large', 'Build=Medium', 'Build=Thin', 'Response']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [58]:
# View the transformed data

Fitness = ['Weight',
          'Build',
        'weight relates Build']


# Use CountVectorizer to convert data

from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer()

X_cv = cv.fit_transform(Fitness)

print(X_cv.toarray())

[[0 0 1]
 [1 0 0]
 [1 1 1]]


In [59]:
# Inspect the feature names

print("The feature names of the text document Fitness are:\n", cv.get_feature_names())

The feature names of the text document Fitness are:
 ['build', 'relates', 'weight']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [60]:
from sklearn.feature_extraction.text import TfidfVectorizer

Fitness = ['Weight',
          'Build',
        'weight relates Build']

vec1 =  TfidfVectorizer()

X_tfv = vec1.fit_transform(Fitness)

print(X_tfv.toarray())

[[0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.51785612 0.68091856 0.51785612]]


In [61]:
# get feature names

print(vec1.get_feature_names())

['build', 'relates', 'weight']


/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [62]:
# Calculate inverse document frequencies (idf)

from sklearn.feature_extraction.text import TfidfTransformer

vec2 =  TfidfTransformer()

X_tft = vec2.fit_transform(X_cv)

print(X_tft.toarray())

[[0.         0.         1.        ]
 [1.         0.         0.        ]
 [0.51785612 0.68091856 0.51785612]]
